version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "kbdharun"
      - "sebastiaanspeck"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    reviewers:
      - "kbdharun"
      - "sebastiaanspeck"
