name: Run set-more-info-link.py

on:
  workflow_dispatch:

jobs:
  run-set-more-info-link:
    runs-on: ubuntu-latest

    name: Run set-more-info-link.py

    env:
      LOG_FILENAME: set-more-info-link.log

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          submodules: true

      - name: Run the script and generate artifact
        run: |
          ./tldr/scripts/set-more-info-link.py -S 2>&1 > $LOG_FILENAME && sort -o $LOG_FILENAME $LOG_FILENAME && cat $LOG_FILENAME
          if [ -s $LOG_FILENAME ]; then
            exit 1
          fi

      - name: Upload artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: set-more-info-link
          path: | 
            $LOG_FILENAME
