name: Run set-alias-page.py

on:
  workflow_dispatch:

jobs:
  run-set-more-info-link:
    runs-on: ubuntu-latest

    name: Run set-alias-page.py

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          submodules: true

      - name: Run the script and generate artifact
        run: |
          ./tldr/scripts/set-alias-page.py -S 2>&1 | tee set-alias-page.log
          if [ -s set-alias-page.log ]; then
            exit 1
          fi

      - name: Upload artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: set-alias-page
          path: | 
            set-alias-page.log
