name: Update Submodule

permissions:
  contents: write
  actions: write

on:
  workflow_dispatch:
  schedule:
    - cron: "10,40 * * * *"

jobs:
  update-submodule:
    name: Update Submodule
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          submodules: true

      - name: Git submodule update
        run: |
          git pull --rebase=true --recurse-submodules
          git submodule update --remote --recursive

      - name: Commit update
        id: commit
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          if git commit -am "ci: update TLDR submodule" && git push; then
            echo "anything-committed=true" >> $GITHUB_OUTPUT
          else
            echo "anything-committed=false" >> $GITHUB_OUTPUT
          fi
        shell: bash

      - name: Trigger Calculate Metrics
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0.0
        if: ${{ steps.commit.outputs.anything-committed == 'true' }}
        with:
          script: |
            github.rest.actions.createWorkflowDispatch({
                owner: context.repo.owner,
                repo: context.repo.repo,
                workflow_id: 'calculate-metrics.yml',
                ref: 'main',
              })
